yoreporto_report:
    resource: "@YoreportoReportBundle/Resources/config/routing.yml"
    prefix:   /

yoreporto_activity:
    resource: "@YoreportoActivityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation