parameters:

services:
#    yoreporto_usuario.example:
#        class: Yoreporto\UsuarioBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: Yoreporto\UsuarioBundle\Listener\LoginListener
        arguments: [@router]
        tags:
          - { name: kernel.event_listener, event: security.interactive_login }
          - { name: kernel.event_listener, event: kernel.response }