services:
#    yoreporto_actividad.example:
#        class: Yoreporto\ActividadBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    yoreporto.form.type.activity:
        class: Yoreporto\ActivityBundle\Form\ActivityType
        tags:
            - { name: form.type, alias: activity }