yoreporto_activity_homepage:
    path:     /hello/{name}
    defaults: { _controller: YoreportoActivityBundle:Default:index }

yoreporto_new_activity:
    path: /new/Activity
    defaults: { _controller: YoreportoActivityBundle:Default:newActivity }

yoreporto_new_report:
    path: /new/Report
    defaults: { _controller: YoreportoActivityBundle:Default:newReport }