yoreporto_activity_homepage:
    path:     /hello/{name}
    defaults: { _controller: YoreportoActivityBundle:Default:index }

yoreporto_new_activity:
    path: /new/Activity
    defaults: { _controller: YoreportoActivityBundle:Default:newActivity }

yoreporto_new_report:
    path: /new/Report
    defaults: { _controller: YoreportoActivityBundle:Default:newReport }

yoreporto_new_weekly_report:
    path: /new/WeeklyReport
    defaults: { _controller: YoreportoActivityBundle:Default:newWeeklyReport }

yoreporto_view_activities:
    path: /view/Activities
    defaults: { _controller: YoreportoActivityBundle:Default:viewActivities }